source: ""
base_url: ""

_enabled_editors:
  - visual
  - content

collections_config:
  pages:
    name: Pages
    path: "/"
    parser: html
    output: true
    filter:
      base: none
      search:
        - "*.html"

editor:
  default_view: visual
