_enabled_editors:
  - visual
  - content

collections_config:
  pages:
    path: ""
    output: true
    filter:
      base: none
      search:
        - "*.html"
    _enabled_editors:
      - visual
      - content

editor:
  default_view: visual
